<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> <!--игнорировать ошибку System.Runtime.CompilerServices.Unsafe is not obey -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="MySql.Data" Version="9.1.0" />
  </ItemGroup>

</Project>